openapi: 3.0.3
info:
  title: Image Extractor API
  version: 1.0.0
  description: Simple API to extract metadata and sha1 from URL pointing to image
paths:
  /api/v1/images/:
    get:
      operationId: images_list
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - images
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedImageList'
          description: ''
    post:
      operationId: images_create
      description: Provide image URL to be analyzed. Response is url where information
        about the image can be found (because image analysis is done in the background).
      tags:
      - images
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImageCreation'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageCreation'
          description: ''
  /api/v1/images/{id}/:
    get:
      operationId: images_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - images
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'
          description: ''
    delete:
      operationId: images_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - images
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    Image:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        url:
          type: string
          maxLength: 250
        hash:
          type: string
        width:
          type: integer
          maximum: 2147483647
          minimum: 0
        height:
          type: integer
          maximum: 2147483647
          minimum: 0
        type:
          type: string
          maxLength: 10
      required:
      - hash
      - id
    ImageCreation:
      type: object
      properties:
        url:
          type: string
          maxLength: 200
      required:
      - url
    PaginatedImageList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Image'
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
