# Generated by Django 3.2.13 on 2022-05-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.BinaryField(max_length=20)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=10)),
            ],
        ),
    ]
